### ISSUE TITLE
Generate an Activity Tracker event for service creation

### ISSUE THREAD

**Issue by rbkonuru** [IBM/cloud-operators#111]
When using the IBM Cloud operator, any service creation results in a service creation event is logged into Activity Tracker. Currently, because of the way IBM Cloud operator  works, the initiator will be corresponding to the API key/service id used by AT instead of the actual user who initiate the service creation.  The request here is to add a feature to Cloud operator to create an additional service creation event that shows the actual user who created the service. 

It might be possible to some how create a service with the user's name, then we don't need another AT event. 

Please contact me if you have any questions.

**Comment by vazirim** [comment]
Creation and deletion events for Service and Binding in AT now appear as follows:

```Apr 8 18:18:57 ibmcloud-operator-6b75744b95-r4s2s ibmcloud-controllers info {"level":"info","ts":1586384337.4595006,"logger":"service","msg":"Creating ","User":<username>,"mytranslator":"language-translator"}```

**Comment by vazirim** [comment]
Fixed in v0.1.7
