### ISSUE TITLE
Failed to delete an `alias` binding CR 

### ISSUE THREAD

**Issue by cdlliuy** [IBM/cloud-operators#121]
I can create a binding CR correctly for the existing service-keys. 
Then I deleted the related service-key from IBMCloud CLI manually.  

I understood that the alias binding CR can't be self-healing to recreate, but I can't delete the failed binding CR. 

```
>>  kubectl delete bindings.ibmcloud.ibm.com ying-translator-credential
binding.ibmcloud.ibm.com "ying-translator-credential" deleted

(cmd hang here..)
>> kubectl get bindings.ibmcloud.ibm.com ying-translator-credential
NAME                         STATUS   AGE
ying-translator-credential   Failed   2d17h
```

I would like to expect the failed resource would be removed.

**Comment by cdlliuy** [comment]
@vazirim  , can you take a look on this?

**Comment by vazirim** [comment]
Hi @cdlliuy, I am unable to reproduce this bug. Can you provide the relevant logs corresponding to this from the ICO's pod?

**Comment by cdlliuy** [comment]
close as resolved.
