### ISSUE TITLE
Use client-gen to autogenerate client code

### ISSUE THREAD

**Issue by ericmillin** [IBM/cloud-operators#125]
Creating a kube go client for CRDs is really painful. It would be great if clients could use one autogenerated from your code.

The code contains all the required annotations. 
https://github.com/IBM/cloud-operators/blob/d176e99190d3441264e41201e99097beaa5d0b75/pkg/apis/ibmcloud/v1alpha1/service_types.go#L65

You just need to run [client-gen](https://github.com/kubernetes/code-generator/tree/master/cmd/client-gen) and commit the client code.

**Comment by vazirim** [comment]
@ericmillin I looked into this issue a bit. You can use controller-runtime to create/update/delete Services and Bindings programmatically. 

The above code generator is not supported in KubeBuilder and currently generates code that has compile time errors. 

Maybe this thread helps: https://github.com/kubernetes-sigs/kubebuilder/issues/1152

**Comment by ericmillin** [comment]
@vazirim How do I get the correct scheme from the cloud-operators package to use with controller-runtime?

**Comment by vazirim** [comment]
@ericmillin yes, here is a sample code:

```package main

import (
	"context"
	"fmt"
	"log"

	"github.com/ibm/cloud-operators/pkg/apis"
	"github.com/ibm/cloud-operators/pkg/apis/ibmcloud/v1alpha1"
	_ "k8s.io/client-go/plugin/pkg/client/auth/oidc"

	"k8s.io/apimachinery/pkg/runtime"
	clientgoscheme "k8s.io/client-go/kubernetes/scheme"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

func main() {

	scheme := runtime.NewScheme()
	_ = clientgoscheme.AddToScheme(scheme)
	_ = apis.AddToScheme(scheme)

	kubeconfig := ctrl.GetConfigOrDie()
	kubeclient, err := client.New(kubeconfig, client.Options{Scheme: scheme})
	if err != nil {
		log.Fatal(err)
	}

	var service v1alpha1.Service
	err = kubeclient.Get(context.Background(), client.ObjectKey{
		Namespace: "default",
		Name:      "mytranslator",
	}, &service)

	if err != nil {
		fmt.Printf(err.Error())
	}

	fmt.Printf("Service is %v", service)

}```
