### ISSUE TITLE
Why does Cloud Operator need Cloud Foundry?

### ISSUE THREAD

**Issue by lionelmace** [IBM/cloud-operators#126]
Most of IBM Cloud Resources are based on an IAM/Resource Group model.

Why do we still need Cloud Found Org and Space to use the operator?

Is there any plan to update the operator to reflect this model change?

**Comment by vazirim** [comment]
Hi @lionelmace, yes when we first developed ICO a lot of services had not yet migrated from CF to the Resource group model, and we supported both. In the future, this support will be removed.
If you do not set `org` and `space` during installation, it should still work.

**Comment by lionelmace** [comment]
@vazirim Great news! Thanks for the update.

**Comment by lionelmace** [comment]
@vazirim any update in regards to remove CF support in the ibm cloud operator.

**Comment by vazirim** [comment]
@JohnStarich ^^^
