### ISSUE TITLE
This operator does not install properly from the operatorHub

### ISSUE THREAD

**Issue by gmendel** [IBM/cloud-operators#140]
It seems that you require one to run the shell script to install this operator.
If one tries to install it via the CSV (from an openshift operator hub
![image](https://user-images.githubusercontent.com/4655019/82955034-f47f5200-9f7b-11ea-9168-af2ba2b88e8c.png)

It will not install properly: creating the sample service generates the following:
```
piVersion: ibmcloud.ibm.com/v1alpha1
kind: Service
metadata:
  creationTimestamp: '2020-05-26T21:11:41Z'
  generation: 1
  name: mytranslator
  namespace: validation
  resourceVersion: '24151'
  selfLink: /apis/ibmcloud.ibm.com/v1alpha1/namespaces/validation/services/mytranslator
  uid: 9686d557-1362-41ce-b8c1-b54577fa4716
spec:
  plan: lite
  serviceClass: language-translator
status:
  context: {}
  message: Secret "secret-ibm-cloud-operator" not found
  plan: ''
  serviceClass: ''
  serviceClassType: ''
  state: Failed
```

**Comment by vazirim** [comment]
Hi @gmendel, you need to follow the instructions (login into IBM Cloud etc...) before installing the operator. This is because the operator needs to have information about your IBM Cloud account (created in the form of secret and configmap when you follow the instructions).

**Comment by pdettori** [comment]
@gmendel as @vazirim said, if you are installing from OperatorHub, follow the instructions under the requirements section (https://operatorhub.io/operator/ibmcloud-operator ). The instructions are slightly different if you are not installing from operator hub (in that case follow the instructions in the this project)
