### ISSUE TITLE
Merge v1.0.0 release PR into community-operators repo

### ISSUE THREAD

**Issue by JohnStarich** [IBM/cloud-operators#206]
Merge a PR into the [community-operators](https://github.com/operator-framework/community-operators) repo for the v1 tagged release of ICO.

Here's a previous release PR as a guide: https://github.com/operator-framework/community-operators/pull/1911

To Do:
* [x] Merge https://github.com/IBM/cloud-operators/pull/194 first (README is used in OLM install page)
* [x] Preview cluster service version (CSV) on [Operator Hub Preview](https://operatorhub.io/preview)
* [x] Cut v1.0.0 tagged release
* [x] Use the CRDs, package.yaml, and clusterserviceversion.yaml artifacts from the tagged release attachments

**Comment by vazirim** [comment]
I would also add test on OpenShift

**Comment by JohnStarich** [comment]
OpenShift has tested out well since #200 went in. I also have good reports from others using the latest on OpenShift 👍

**Comment by JohnStarich** [comment]
Community PR has been merged: https://github.com/operator-framework/community-operators/pull/2379

**Comment by JohnStarich** [comment]
Closing since OpenShift PR is merged and available on the OpenShift console install screen 🎉 

The second, upstream k8s PR is also now open here: https://github.com/operator-framework/community-operators/pull/2398
