### ISSUE TITLE
FEATURE: Leverage IAM identity of kubernetes user when applicable (IKS and Red Hat OpenShift on IBM Cloud)

### ISSUE THREAD

**Issue by kitch** [IBM/cloud-operators#23]
When using IKS or Red Hat OpenShift on IBM Cloud users are authenticating with openshift/kubernetes with an IBM Cloud IAM identity. Any thoughts on if it would be possible to use this identity for authentication with IBM Cloud when trying to manage the services?

It may be a pipedream, but I do think it's worth investigation to see if there could be a method for leveraging this identity.

**Comment by vazirim** [comment]
We use the info in seed-secret and generate IAM tokens. We authenticate with IBM Cloud using those tokens. These are currently refreshed fairly frequently.

Is this what you are asking?

**Comment by kitch** [comment]
I think for now I'm just going to close this one :) I've been noodling on it a bit more and I'm not really convinced it makes sense at the moment. I am going to do a bit more research on the potential to leverage the kube users identity for authz with IAM (IKS users have an IAM identity) but it would require some impersonation support from IAM and ibm cloud which may or may not be there. There is also the issue that the objects that the operator is acting upon dont have any user context which kind of defeats the purpose.

**Comment by pdettori** [comment]
@kitch let me know if we can close this one.
