### ISSUE TITLE
Automated OperatorHub releases

### ISSUE THREAD

**Issue by marrau** [IBM/cloud-operators#247]
The version of the cloud-operator at operatorhub.io  => https://operatorhub.io/operator/ibmcloud-operator/
is outdated.
Can you make this update automatically with every release!?

**Comment by JohnStarich** [comment]
Thanks for opening @marrau. This is something we made some strides toward, but have not yet completed.

As usual, PRs are welcome 😄

**Comment by arturobrzut** [comment]
Hi @JohnStarich 
We (Bedrock/ Common services) also need it

Or we need to change installation process

**Comment by JohnStarich** [comment]
I've got some time to work on this. If all goes well, should have some automation done by end of next week. Ideally fully automated, but we'll see!

**Comment by JohnStarich** [comment]
Some relevant links I've been referring to:
* The new location for Kubernetes operators: https://github.com/k8s-operatorhub/community-operators/tree/main/operators/ibmcloud-operator
* The new location for OpenShift operators: https://github.com/redhat-openshift-ecosystem/community-operators-prod/tree/main/operators/ibmcloud-operator
* Submission procedure: https://operator-framework.github.io/community-operators/
* Automated PR merges: https://operator-framework.github.io/community-operators/operator-ci-yaml/#reviewers

**Comment by JohnStarich** [comment]
FYI `v1.0.10` has been released using some of the automation I've been working on. Will close this issue once the automation has been merged.
