### ISSUE TITLE
Deletion of Service/Binding CRD instances failed to delete service instance

### ISSUE THREAD

**Issue by dgrove-oss** [IBM/cloud-operators#40]
Context:

I was testing an example application example that uses an instance of the Watson Language Translator from the IBM cloud.   I was using an IKS 1.14.x cluster with cloudoperators/ibmcloud-operator:0.1.0 installed.

At the start of a sequence of operations, I had no instances of binding or service CRDs in the cluster and no instances of the Watson Language Translator in my cloud account.

At the end of a sequence of operations, I had no instances of binding or service CRDs in the cluster, BUT there was still an instance of the Watson Language Translator in my cloud account (still there 24 hours later).  Based on the name of the instance, it was the one  created by the ibmcloud operator and not deleted when the CRDs were deleted.

Attached is the relevant section of logs from the operator.

[log.txt](https://github.com/IBM/cloud-operators/files/3462437/log.txt)

**Comment by vazirim** [comment]
in the service that remained, is there still a credential?

**Comment by dgrove-oss** [comment]
yes.  there was still a credential.

**Comment by vazirim** [comment]
what's weird is that the log actually indicates that the service was deleted without errors. The first time it fails, but it tries again and the second deletion went through without errors. The binding then is unable to delete because when the service deletion is successful the service and binding kube objects went away. 

I am unable to reproduce. If there is any other detail you can convey, maybe the timing of operations. Are all the yamls submitted together? How long do you wait between creation and deletion?

**Comment by vazirim** [comment]
Are you sure that when you refresh the console in bluemix, the service is still there? 

It is also possible that bluemix returned a 410 on the second deletion indicating that the service has been deleted previously. In that case, our controller would silently do nothing. In all other cases it would have returned and logged the error

**Comment by dgrove-oss** [comment]
The service was in bluemix 24 hours later.  Multiple refreshes of the console page.

I created/deleted relatively the resources relatively quickly.  Then noticed hours later (but still yesterday) that the service was still there.   I checked again today before opening the bug and the service was there.  I have since manually deleted it (so I could recreate it again with the operator).  So far today have created/deleted 3 times with no problems.

**Comment by vazirim** [comment]
ok thanks. I also asked the Watson Translator folks to understand under what situation we get the error `The resource key cannot be deleted`. Maybe that will give us a clue to reproduce.

**Comment by dgrove-oss** [comment]
Had it happen again, this time when using an RHOS 3 cluster.   Attaching log.  I'll leave the translator service instance alive until Monday in case there is anything useful to get by examining it.
[log22.txt](https://github.com/IBM/cloud-operators/files/3463054/log22.txt).

**Comment by vazirim** [comment]
This was due to a bug in the way we were checking if a service doesn't exist upon deletion. The bug has been fixed in PR #41

**Comment by vazirim** [comment]
@dgrove-oss please let me know if we can close this issue now

**Comment by dgrove-oss** [comment]
Have not seen problem since I updated to new version of operator.  Closing.
