### ISSUE TITLE
install-operator.sh is failed due to I don't know how to create secret

### ISSUE THREAD

**Issue by takara9** [IBM/cloud-operators#42]
$ curl -sL https://raw.githubusercontent.com/IBM/cloud-operators/master/hack/install-operator.sh | bash 
* Downloading install yaml...
error: error validating "STDIN": error validating data: [unknown object type "nil" in Secret.data.api-key, unknown object type "nil" in Secret.data.region]; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by vazirim** [comment]
Hi @takara9, this means that your IBM Cloud settings have not been initialized properly. Please follow the Requirements section of the README.

**Comment by aslom** [comment]
I have similar error - I followed requirements.

```
(base) aslom@m dev-aiwf $ ibmcloud target --cf
Targeted Cloud Foundry (https://api.us-east.bluemix.net)

Targeted org aslom@us.ibm.com


Select a space (or press enter to skip):
1. tutorial2
2. dev01
Enter a number> 2
Targeted space dev01



API endpoint:      https://cloud.ibm.com
Region:            us-east
User:              aslom@us.ibm.com
Account:           Aleksander Slominski's Account (e3a470d882f9e5b9a59f4c98b6cb2b40) <-> 1729777
Resource group:    No resource group targeted, use 'ibmcloud target -g RESOURCE_GROUP'
CF API endpoint:   https://api.us-east.bluemix.net (API version: 2.128.0)
Org:               aslom@us.ibm.com
Space:             dev01
(base) aslom@m dev-aiwf $ curl -sL https://raw.githubusercontent.com/IBM/cloud-operators/master/hack/install-operator.sh | bash
* Downloading install yaml...
secret/seed-secret created
Error from server (BadRequest): error when creating "STDIN": ConfigMap in version "v1" cannot be handled as a ConfigMap: v1.ConfigMap.Data: ReadString: expects " or n, but found f, error found in #10 byte of ...|ceGroup":false,"spac|..., bigger context ...|m@us.ibm.com","region":"us-east","resourceGroup":false,"space":"dev01"},"kind":"ConfigMap","metadata|...
```

Any idea what may be causing the error?

**Comment by vazirim** [comment]
Hi @aslom,

In the above target context, the Resource Group is nil. This must be a change in IBM Cloud (it used to be set to `default` if not specified). You need to do the following as well:

`ibmcloud target -g default`

which will set the resource group to `default`.

Please try and let me know if if fixes your issue.
We will update the documentation accordingly.

**Comment by pdettori** [comment]
Doc has been updated as described.
