### ISSUE TITLE
account information checks from config-operator.sh

### ISSUE THREAD

**Issue by timroster** [IBM/cloud-operators#72]
Sometimes when using the IBM Cloud CLI, the region is not being set resulting in `IC_REGION` being empty. This results in rather obscure errors during secret creation like:

`error: error validating “STDIN”: error validating data: unknown object type “nil” in Secret.data.region; if you choose to ignore these errors, turn validation off with --validate=false`

It would be helpful to do a quick validation of the `IC...` fields in this script and putting up an error message to help users spot and fix the CLI session configuration issue.

**Comment by JohnStarich** [comment]
@timroster thanks for re-checking! I've got a PR up now that addresses this for required fields 👍
