### ISSUE TITLE
[Question] Where does the olm was published

### ISSUE THREAD

**Issue by gyliu513** [IBM/cloud-operators#80]
I found that we have a folder for olm https://github.com/IBM/cloud-operators/tree/master/olm , the question is for on-line install, where I can get those olm files? From operatorhub or some other places?

**Comment by pdettori** [comment]
You should just use OperatorHub.io ... we generate the OLM files and publish them there via PR.

**Comment by gyliu513** [comment]
I saw it was here https://github.com/operator-framework/community-operators/tree/master/community-operators/ibmcloud-operator , but this will cause the operator publisher will be `Red Hat` but not `IBM`, is this expected?

**Comment by pdettori** [comment]
That project (community operator) is where contributors to OperatorHub can make PRs that end up in OperatorHub catalog. The contributed operator shows the company name that is contributing it (e.g. https://operatorhub.io/?category=Cloud+Provider&provider=%5B%22IBM%22%5D ). Do you have some specific use case in mind ?

**Comment by gyliu513** [comment]
Ah, I see, thanks @pdettori , this make sense.

**Comment by pdettori** [comment]
You are welcome @gyliu513 !
