### ISSUE TITLE
Document behavior of `self-healing` annotation

### ISSUE THREAD

**Issue by seansund** [IBM/cloud-operators#87]
There is a closed issue (#11) that added an annotation to control the `self-healing` behavior and there is at least one example that includes the self-healing annotation.

However, there is no documentation anywhere else as to what exactly this is doing and how to apply it. I believe this annotation will address an issue on my project but I'm hesitant to use it without getting a better understanding of how it works.

**Comment by vazirim** [comment]
@seansund This annotation is no longer in use. The default behavior is self-healing, meaning if you delete the service instance manually on bluemix, the operator will recreate it. 

What is the issue you are experiencing?
