### ISSUE TITLE
Question: The secret in the binding, can it be revoked or rotated?

### ISSUE THREAD

**Issue by carltonmason** [IBM/cloud-operators#88]
The [usage docs](https://github.com/IBM/cloud-operators/blob/master/docs/user-guide.md#creating-a-binding) describe:
> A Binding generates a secret with the same name as the binding resource and contains service credentials that can be consumed by your application.

Is there anyway to revoke or rotate the secret?  

Thinking of use cases where the secret has been compromised or if it needs to be rotated periodically due to some biz security policy.

If there is a better place to ask such questions please let me know.

Thank You

**Comment by pdettori** [comment]
@carltonmason this sounds like a valid use case. There is not currently a way to manage this automatically, although something along this lines might be accomplished with some external tool that deletes and re-creates the binding, forcing the operator to request new credentials from the service and re-create the secret.

**Comment by pdettori** [comment]
One possible approach could be to specify something like a time-to-live in the specs for the binding, so that once that time is reached the credentials are refreshed and the secret is re-generated (need to figure out if it would be better to just update or re-create the secret)

**Comment by carltonmason** [comment]
Hi @pdettori .   Yes, the current limitation may prevent us from using this cloud operator given our increasing compliance requirements.

I can see how designing such a solution will require some care and security wits given the sensitivity of secret, who can revoke it or recreate it, etc...

What is the process for getting this considered as an official feature request?

Thanks

**Comment by vazirim** [comment]
Hi @carltonmason, so the feature request is to add a time-to-live in the Binding spec so that it refreshes itself after that time? Please confirm and I will implement it.

**Comment by carltonmason** [comment]
@vazirim  helped me via Slack.  Seems deleting and recreating the binding will create a new secret and thus addresses both my question and requirement.  Closing this issue.  Thanks
