### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by pdettori** [IBM/cloud-operators#90]
Document the following:
- When a binding is deleted the associated secret is deleted as well. One way to refresh credentials is to delete a binding and recreate
- Document the meaning of all optional parameters of Service and Binding
- Elaborate on how to obtain service and plan names
- Explain global region in the context for some services
- Explain why some services display an inactive or failed status until they become online (that we simply channel the status coming from Bluemix)
- Add section on Credential aliases
- Add section on immutability of some fields in Service spec

**Comment by zhlsunshine** [comment]
Here is the list I hope your team to improve on IBM Cloud Operator Doc:

- [ ] For IBM Cloud Operator, how could I officially retrieve the Service Class and Plan list, such as: **ibmcloud catalog service-marketplace** and **ibmcloud catalog service <SERVICE_CLASS> | grep plan**

- [ ] For some services, my provisioning fail via IBM Cloud Operator when I choose other plan except lite, and I also get this error information:  

> Failed: No deployment found for service plan extension-for-apache-couchdb at location us-south. Valid location(s) are: ["global"]. Use service instance example if the service is a Cloud Foundry service”
 
  I have to correct the plan with **global** region. So I hope I can find the answer for _what are all constrictions for the service plan_ and _how do they perform when I provision service_? from the doc

- [ ] When I provision service via IBM Cloud Operator, the service can be in inactive, showing as below:  
<img width="964" alt="image" src="https://user-images.githubusercontent.com/4101246/76194988-4d173c80-6222-11ea-8f3b-ae3d2f27e17b.png">
  I do not think it’s normal but I can not get any explanation or information about this status, is it in provisioning or provision failed?

**Comment by vazirim** [comment]
Fixed in v0.1.5
