### ISSUE TITLE
Use UBI image as the base image?

### ISSUE THREAD

**Issue by cdlliuy** [IBM/cloud-operators#94]
Is that possible to publish ibm-cloud-operator with http://registry.access.redhat.com/ubi8-minimal image?

**Comment by dcberg** [comment]
Since this is a golang application, it should be possible to create a "scratch" image which would be smaller and more secure than even a UBI image.

**Comment by cdlliuy** [comment]
@dcberg ,  it is just due to requirement of service framework ..

**Comment by cdlliuy** [comment]
add https://github.com/IBM/cloud-operators/pull/113 for this

**Comment by pdettori** [comment]
@cdlliuy just to understand better ... is it the case that the "scratch" image would not work for you because you need the ca certificates in the image ?

**Comment by vazirim** [comment]
Fixed in v0.1.7
