### ISSUE TITLE
Put seed-default /seed-secrets into an `admin-only` accessible workspace

### ISSUE THREAD

**Issue by cdlliuy** [IBM/cloud-operators#95]
Per @paolo, Another one is to create secrets in an admin-only accessible workspace, with some naming convention, such as ico-secret-<namespace name> and have the operator look up there as well to get the API key. This way we can keep a even better separation and use kube best practices for management of secrets.

Let us use this issue to track this feature development.

**Comment by vazirim** [comment]
This is the same issue as #91

**Comment by pdettori** [comment]
Closing in favor of https://github.com/IBM/cloud-operators/issues/91 , where I added more details on the design proposal.
