### ISSUE TITLE
Rename seed-default and seed-secrets

### ISSUE THREAD

**Issue by cdlliuy** [IBM/cloud-operators#99]
Per discussion in #91,  I created a new issue to bring this up

===================

@pdettor I just curious, are the names seed-secret and seed-defaults configurable? If we put them into the end-user's namespace where the service/bind resource being created, I would like to use a more explicitly name , i.e. secret-ibm-cloud-operator and config-ibm-cloud-operator to avoid the deletion by end-user.

Answered by @vazirim
@cdlliuy Sure, we can rename.

===================

**Comment by vazirim** [comment]
This item is already part of #91
